[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
risc0-zkvm = { path = "../../risc0/zkvm" }
risc0-zkvm-methods = { path = "../../risc0/zkvm/methods" }
workerpool = "1.2"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
