[package]
name = "rzup"
version = "0.2.1"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1.0.86"
cfg-if = "1.0.0"
clap = { version = "4.5.13", features = ["derive"] }
dirs = "5.0.1"
flate2 = "1.0.31"
fs2 = "0.4.3"
fs_extra = "1.3.0"
lazy_static = "1.5.0"
regex = "1.10.6"
reqwest = { version = "0.12.5", features = ["json", "rustls-tls"] }
risc0-build = { path = "../risc0/build" }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
tar = "0.4.41"
tempfile = "3.10.1"
termcolor = "1.4.1"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["rt-multi-thread", "macros"] }
xz = "0.1.0"
